---
abstract: 'Dist::Zilla plugin bundle used by Plicease'
author:
  - 'Graham Ollis <perl@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '0.94'
  perl: '5.008001'
configure_requires:
  Module::Build: '0.3601'
  perl: '5.006'
dynamic_config: '1'
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-PluginBundle-Author-Plicease
no_index:
  directory:
    - profiles
    - corpus
recommends:
  PerlX::Maybe::XS: '0'
  YAML::XS: '0'
requires:
  Dist::Zilla: '5.020'
  Dist::Zilla::Plugin::AutoMetaResources: '1.20'
  Dist::Zilla::Plugin::CopyFilesFromBuild: '0'
  Dist::Zilla::Plugin::InstallGuide: '1.200003'
  Dist::Zilla::Plugin::MinimumPerl: '1.003'
  Dist::Zilla::Plugin::OurPkgVersion: '0.005001'
  Dist::Zilla::Plugin::PodWeaver: '4.006'
  Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.142470'
  Dist::Zilla::Plugin::Run::BeforeBuild: '0.026'
  File::chdir: '0'
  IPC::System::Simple: '1.25'
  JSON::PP: '0'
  Moose: '0'
  Path::Class: '0.31'
  PerlX::Maybe: '0.003'
  Test::Fixme: '0.14'
  Test::Pod: '1.44'
  Test::Pod::Coverage: '1.08'
  Test::Version: '1.002001'
  YAML: '0'
  autodie: '0'
  namespace::autoclean: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/issues
  homepage: http://perl.wdlabs.com/Dist-Zilla-PluginBundle-Author-Plicease
  repository: git://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease.git
version: '1.62'
